---
- name: "Configure | RedHat | Create config File"
  template:
    src: "named.conf.j2"
    dest: "{{ named_conf_file_location }}"
    owner: "{{ named_user }}"
    group: "{{ named_group }}"
    mode: "0640"
  when: ansible_os_family == "RedHat"
  notify: Reload named - RedHat

- name: "Configure | RedHat | Create included.conf File"
  template:
    src: "included.conf.j2"
    dest: "{{ named_conf_includes_directory }}/included.conf"
    owner: "{{ named_user }}"
    group: "{{ named_group }}"
    mode: "0640"
  when: ansible_os_family == "RedHat"
  notify: Reload named - RedHat

- name: "Configure | RedHat | Create zone Files"
  template:
    src: "zone.j2"
    dest: "{{ named_conf_directory }}/masters/{{ item.key | regex_replace('_', '.') }}.zone"
    owner: "{{ named_user }}"
    group: "{{ named_group }}"
    mode: "0640"
  with_dict: "{{ named_zones }}"
  when: named_zones_create_masters and ansible_os_family == "RedHat"
  notify: Reload named - RedHat
