---
- name: "Configure | Create monit File"
  template:
    src: "monit.conf.j2"
    dest: "{{ named_monit_conf_directory }}/named"
    owner: "{{ named_user }}"
    group: "{{ named_group }}"
    mode: "0600"
  notify: Reload monit
  when: named_monit_enable

- name: "Configure | Ensure that 'named' is enabled and started"
  service:
    name: "{{ named_service_name }}"
    enabled: True
    state: started
