---
- name: "Install | Ensure 'LOG' directory exists"
  file:
    path: "{{ named_conf_logging_file_directory }}"
    owner: "{{ named_user }}"
    group: "{{ named_group }}"
    state: "directory"
    mode: "0770"

- name: "Install | Ensure 'INCLUDES' directory exists"
  file:
    path: "{{ named_conf_includes_directory }}"
    owner: "{{ named_user }}"
    group: "{{ named_group }}"
    state: "directory"

- name: "Install | Ensure 'Master-zones' directory exists"
  file:
    path: "{{ named_conf_directory }}/masters"
    owner: "{{ named_user }}"
    group: "{{ named_group }}"
    state: "directory"
