---
# Maybe later we can add some removal tasks
- include: install_base.yml
  tags:
    - install

- include: install_debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - install

- include: install_redhat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - install

- include: configure_base.yml
  tags:
    - configure

- debug:
    var: named_zones

- include: configure_debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - configure

- include: configure_redhat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - configure

- include: local_facts.yml
  tags:
    - gather_facts
