---
- name: "Reload named - RedHat"
  service:
    name: "{{ named_service_name }}"
    state: reloaded
  when: ansible_os_family == "RedHat"

- name: "Reload named - Debian"
  service:
    name: "bind9"
    state: reloaded
  when: ansible_os_family == "Debian"

- name: "Reload monit"
  service:
    name: "{{ named_monit_service_name }}"
    state: reloaded
